name: yusic
description: "Yusic - Professional Music Studio Booking & Artist Management Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.2
  
  # Storage & Database
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  
  # Networking
  http: ^1.2.1
  dio: ^5.4.3
  
  # Authentication & Security
  flutter_secure_storage: ^9.2.2
  
  # File Handling
  file_picker: ^8.0.0
  image_picker: ^1.1.2
  
  # Audio
  audioplayers: ^6.0.0
  just_audio: ^0.9.38
  
  # Calendar & Date
  table_calendar: ^3.1.2
  intl: ^0.19.0
  
  # Payment Integration
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  
  # UI Utilities
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  fluttertoast: ^8.2.5
  
  # Utils
  uuid: ^4.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/